language: python
    
install:
    - pip install tox 
script:
    - tox
env:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34

matrix:
    allow_failures:
        - env: TOXENV=py33
        - env: TOXENV=py34
