language: python
install:
    - pip install tox 
script:
    - tox
env:
    - TOXENV=py26-r24
    - TOXENV=py26-r25
    - TOXENV=py26-r26
    - TOXENV=py26-r27

    - TOXENV=py27-r24
    - TOXENV=py27-r25
    - TOXENV=py27-r26
    - TOXENV=py27-r27
    - TOXENV=py27-r30
    - TOXENV=py27-r31

    - TOXENV=py33-r30
    - TOXENV=py33-r31

    - TOXENV=py34-r30
    - TOXENV=py34-r31
